export const settingsData = {
  privacy: {
    title: "Privacy Policy",
    content:
      "Chicken Health Tracker Privacy Policy\n\nEffective Date: March 10, 2025\n\n1. Information We Collect\n\nThe Chicken Health Tracker app collects the following information:\n- Chicken health records you create\n- Inspection history you input\n- App preferences and settings\n\nAll data is stored locally on your device using localStorage and is not transmitted to our servers.\n\n2. How We Use Your Information\n\nThe information you provide is used solely to:\n- Display your chicken health records within the app\n- Track inspection history\n- Improve app functionality\n\n3. Data Storage and Security\n\nAll data is stored locally on your device. We recommend regularly backing up your device to prevent data loss.\n\n4. Your Rights\n\nYou have the right to:\n- Access all your data within the app\n- Delete your data by clearing the app's localStorage\n- Use the app without providing any personal information\n\n5. Changes to This Policy\n\nWe may update this privacy policy from time to time. We will notify you of any changes by posting the new privacy policy in the app.\n\n6. Contact Us\n\nIf you have any questions about this privacy policy, please contact us at support@chickenhealth.example.com.",
  },
  terms: {
    title: "Terms of Use",
    content:
      'Chicken Health Tracker Terms of Use\n\nEffective Date: March 10, 2025\n\n1. Acceptance of Terms\n\nBy using the Chicken Health Tracker app, you agree to these Terms of Use. If you do not agree, please do not use the app.\n\n2. App License\n\nWe grant you a limited, non-exclusive, non-transferable license to use the Chicken Health Tracker app for your personal, non-commercial purposes.\n\n3. User Responsibilities\n\nYou are responsible for:\n- Maintaining the confidentiality of your device\n- All activities that occur on your device\n- Ensuring that your use of the app complies with applicable laws\n\n4. App Content and Functionality\n\nThe health recommendations provided in this app are for informational purposes only and should not replace professional veterinary advice.\n\n5. Intellectual Property\n\nAll content, features, and functionality of the Chicken Health Tracker app are owned by us and are protected by copyright, trademark, and other intellectual property laws.\n\n6. Disclaimer of Warranties\n\nThe app is provided "as is" without warranties of any kind, either express or implied.\n\n7. Limitation of Liability\n\nWe shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of, or inability to use, the app.\n\n8. Changes to Terms\n\nWe may update these Terms of Use from time to time. We will notify you of any changes by posting the new Terms of Use in the app.\n\n9. Governing Law\n\nThese Terms of Use shall be governed by and construed in accordance with the laws of the United States.\n\n10. Contact Us\n\nIf you have any questions about these Terms of Use, please contact us at support@chickenhealth.example.com.',
  },
  support: {
    title: "Support",
    content:
      'Chicken Health Tracker Support\n\nWe\'re here to help you get the most out of your Chicken Health Tracker app.\n\nFrequently Asked Questions\n\nQ: How do I add a new chicken to my flock?\nA: Go to the Checklist page and tap the "Add Chicken" button at the top of the screen. Enter the chicken\'s ID and health status, then tap "Add Chicken".\n\nQ: How do I edit a chicken\'s information?\nA: On the Checklist page, find the chicken you want to edit and tap the pencil icon. Update the information and tap "Save Changes".\n\nQ: Will I lose my data if I uninstall the app?\nA: Yes. The app uses localStorage to store your data, which is cleared when you uninstall the app. We recommend taking screenshots of important information before uninstalling.\n\nQ: How do I reset the onboarding tutorial?\nA: Go to your device\'s browser settings, find the site data for this app, and clear the localStorage. This will reset all app data including the onboarding flag.\n\nContact Information\n\nFor additional support, please contact us at:\n\nEmail: support@chickenhealth.example.com\nWebsite: www.chickenhealth.example.com/support\nPhone: (555) 123-4567\n\nAvailable Monday-Friday, 9:00 AM - 5:00 PM Eastern Time.',
  },
}

